### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Nikros28** [eoleedi/TimeTree-exporter#27]
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\timetree-exporter.exe\__main__.py", line 4, in <module>
ImportError: cannot import name 'main' from 'timetree_exporter.__main__' (C:\Python312\Lib\site-packages\timetree_exporter\__main__.py)`
What is the Problem?

**Comment by eoleedi** [comment]
Ahh my bad
It should work after #28 is merged and updated to PyPI.
